#!/usr/bin/env python3
"""
_rebuild_generator.py — Reconstruye nucleo/generator.syn desde los submódulos
en nucleo/generador/.

ORDEN DE CONCATENACIÓN (estricto):
  1. nucleo/generador/contexto.syn     — Estado y tipos del generador nativo
  2. nucleo/generador/emision_c.syn     — API de emisión de código C de bajo nivel
  3. nucleo/generador/nodos_flujo.syn   — Visitantes de control de flujo (OO style)
  4. nucleo/generador/orquestador.syn   — Orquestador del generador nativo

NOTA: nucleo/generador/compilar.syn es un submódulo independiente usado por
principal.syn directamente, NO forma parte del generador combinado.

USO:
    python nucleo/_rebuild_generator.py

SALIDA:
    Escribe nucleo/generator.syn con codificación UTF-8 pura.
"""

import os
import sys

SUB_MODULOS = [
    "contexto.syn",
    "emision_c.syn",
    "expr_eval.syn",       # _oo_expr_a_c (extraido de nodos_flujo.syn para < 1000 lineas)
    "nodos_flujo.syn",
    "frontend_nativo.syn", # Wrapper del frontend nativo (A3.2/A4): gen_emitir_frontend_nativo.
                          # El espejo embebido frontend_p.syn (_P_*) se retiro en A4.
    "escaneo.syn",         # Modularizacion (AUDITORIA): escaneo de estructuras/retornos/alias/constructores
                          # (extraido de orquestador.syn; bloques ME-B4/ME-B6/ME-F1.2b/ME-D6)
    "monomorfizacion.syn", # Modularizacion: registro de ADT genericos + scan D-2 de instanciaciones
                          # (extraido de orquestador.syn; bloque ME-D2, R16/R17/R18)
    "recorrido.syn",       # Modularizacion: walk top-level del AST en orden alfabetico
                          # (extraido de orquestador.syn; bloque WALK)
    "funciones.syn",       # Modularizacion (AUDITORIA 13): emision de funciones de usuario
                          # (extraido de la rama DefinicionFuncion de gen_visitar_top_level)
    "orquestador.syn",     # Debe ir DESPUES de frontend_nativo.syn (hook ME-B7 lo invoca) y de
                          # los modulos extraidos en la modularizacion (los invoca en orden)
]

DIR_GENERADOR = os.path.join(os.path.dirname(__file__), "generador")
SALIDA = os.path.join(os.path.dirname(__file__), "generator.syn")

HEADER = """// Combined generator module (from generador/ sub-modules)
// Auto-generated by _rebuild_generator.py
// Edit files in nucleo/generador/, then run:
//     python nucleo/_rebuild_generator.py


"""

SEPARATOR_TEMPLATE = """
// ===== From: {filename} =====

"""


def _extraer_lang_header(texto: str) -> str:
    """Extrae la línea #lang: si existe y la retorna, o vacío si no."""
    lineas = texto.splitlines(keepends=True)
    if lineas and lineas[0].startswith("#lang:"):
        return lineas[0].rstrip()
    return ""


def reconstruir() -> int:
    """Reconstruye generator.syn desde los submódulos. Retorna 0 si éxito, 1 si error."""
    partes = []
    lang_header = ""
    errores = 0

    for nombre_mod in SUB_MODULOS:
        ruta = os.path.join(DIR_GENERADOR, nombre_mod)
        if not os.path.isfile(ruta):
            print(f"[ERROR] No encontrado: {ruta}")
            errores += 1
            continue
        try:
            with open(ruta, "r", encoding="utf-8") as f:
                contenido = f.read()
        except UnicodeDecodeError as e:
            print(f"[ERROR] Codificación no UTF-8 en {ruta}: {e}")
            # Intentar leer como latin-1 y re-escribir como UTF-8
            try:
                with open(ruta, "r", encoding="latin-1") as f:
                    contenido_latin1 = f.read()
                contenido = contenido_latin1.encode("latin-1").decode("utf-8", errors="replace")
                print(f"  [WARN] {nombre_mod}: Re-codificado de latin-1 a UTF-8")
            except Exception as e2:
                print(f"  [ERROR] No se pudo recuperar {nombre_mod}: {e2}")
                errores += 1
                continue

        # Extraer #lang: de solo el primer archivo
        if nombre_mod == "contexto.syn":
            lang_header = _extraer_lang_header(contenido)
            if lang_header:
                # Remover #lang: del contenido (irá en el header global)
                lineas = contenido.splitlines(keepends=True)
                if lineas and lineas[0].startswith("#lang:"):
                    contenido = "".join(lineas[1:]).lstrip("\n\r")

        print(f"  [OK] {nombre_mod}: {len(contenido)} caracteres")
        separator = SEPARATOR_TEMPLATE.format(filename=nombre_mod)
        partes.append(separator)
        partes.append(contenido)

    if errores > 0:
        print(f"\n[ERROR] {errores} submódulo(s) no procesados. Abortando.")
        return 1

    # Construir contenido final
    contenido_final = HEADER
    if lang_header:
        contenido_final = f"{lang_header}\n" + contenido_final.lstrip()
    contenido_final += "".join(partes)

    # Escribir salida con UTF-8 estricto
    try:
        with open(SALIDA, "w", encoding="utf-8", newline="\n") as f:
            f.write(contenido_final)
        print(f"\n[OK] Generator reconstruido: {SALIDA}")
        print(f"     Tamaño: {len(contenido_final)} caracteres")
        return 0
    except Exception as e:
        print(f"[ERROR] No se pudo escribir {SALIDA}: {e}")
        return 1


if __name__ == "__main__":
    print("=== _rebuild_generator.py ===")
    print(f"  Directorio: {DIR_GENERADOR}")
    print(f"  Salida:     {SALIDA}\n")
    sys.exit(reconstruir())
