#ifndef AST_NODOS_H
#define AST_NODOS_H
// cumple Manual 2 3: tabla canónica de tokens AST
// cumple Manual 2 7: tabla canónica de nodos AST

/*
 * ast_nodos.h — Tabla canónica de constantes AST para el runtime C.
 *
 * Fuente única de verdad: nucleo/parser_constantes.syn
 *   - TokenID (T_*): Manual 2 §3 / Manual 2 §2.3
 *   - NodoID (NODO_*): Manual 2 §7.2 (extracto ilustrativo) / Manual 2 §7.3
 *
 * ABI v1 CONGELADA (F22/R85, nucleo/ast_abi.syn).
 * Los valores del Manual 2 §7.2 "(Extracto)" son ILUSTRATIVOS;
 * los valores canónicos vigentes están en parser_constantes.syn.
 *
 * AUTO-VERIFICADO por tests/unit/test_ast_nodos_consistency.py
 * NO EDITAR MANUALMENTE — regenere con scripts/gen_ast_nodos_h.py.
 *
 * Incluir como:  #include "runtime/core/ast_nodos.h"
 */

/* === Token ID constants (Manual 2 §3) === */
#define T_SI                 (1LL)
#define T_SINO               (2LL)
#define T_FUNCION            (3LL)
#define T_RETORNAR           (4LL)
#define T_LANZAR             (5LL)
#define T_RECUPERAR          (6LL)
#define T_ESCUCHAR           (7LL)
#define T_MIENTRAS           (8LL)
#define T_IMPORTAR           (9LL)
#define T_ESTRUCTURA         (10LL)
#define T_ROMPER             (11LL)
#define T_SIGUIENTE          (12LL)
#define T_PUNTO              (13LL)
#define T_Y                  (14LL)
#define T_O                  (15LL)
#define T_NO                 (16LL)
#define T_VERDADERO          (17LL)
#define T_FALSO              (18LL)
#define T_IDENTIFICADOR      (19LL)
#define T_NUMERO             (20LL)
#define T_FLOTANTE           (21LL)
#define T_CADENA             (22LL)
#define T_MAYOR              (23LL)
#define T_MENOR              (24LL)
#define T_IGUAL              (25LL)
#define T_DISTINTO           (26LL)
#define T_MENOR_IGUAL        (27LL)
#define T_MAYOR_IGUAL        (28LL)
#define T_ASIGNAR            (29LL)
#define T_MAS                (30LL)
#define T_MENOS              (31LL)
#define T_POR                (32LL)
#define T_DIV                (33LL)
#define T_MOD                (34LL)
#define T_FLECHA             (35LL)
#define T_COINCIDIR          (36LL)
#define T_FLECHA_DER         (37LL)
#define T_PAREN_IZQ          (38LL)
#define T_PAREN_DER          (39LL)
#define T_DOSPUNTOS          (40LL)
#define T_COMA               (41LL)
#define T_NUEVALINEA         (42LL)
#define T_INDENTAR           (43LL)
#define T_DESINDENTAR        (44LL)
#define T_AMPERSAND          (45LL)
#define T_INSEGURO           (46LL)
#define T_IMPORTAR_C         (47LL)
#define T_EXTERNO            (48LL)
#define T_FLECHA_IZQ         (49LL)
#define T_REQUIERE           (50LL)
#define T_GARANTIZA          (51LL)
#define T_CANAL              (52LL)
#define T_ASM                (53LL)
#define T_CONSTANTE          (54LL)
#define T_PUNTOCOMA          (55LL)
#define T_PARA               (56LL)
#define T_FIN                (57LL)
#define T_LET                (59LL)
#define T_TIPO               (60LL)
#define T_TENSOR             (61LL)
#define T_NULO               (62LL)
#define T_OK                 (63LL)
#define T_ERR                (64LL)
#define T_ALGUN              (65LL)
#define T_NINGUNO            (66LL)
#define T_MODULO             (67LL)
#define T_DELEGAR            (68LL)
#define T_EXPORT             (69LL)
#define T_RC                 (70LL)
#define T_ARC                (71LL)
#define T_DEBIL              (72LL)
#define T_PIPE               (73LL)
#define T_INTERROGACION      (74LL)

/* === AST node type constants (Manual 2 §7.2/§7.3) === */
#define NODO_PROGRAMA            (1LL)
#define NODO_FUNCION             (2LL)
#define NODO_SI                  (3LL)
#define NODO_MIENTRAS            (4LL)
#define NODO_RETORNAR            (5LL)
#define NODO_EXPR                (6LL)
#define NODO_ASIGNACION          (7LL)
#define NODO_IDENTIFICADOR       (8LL)
#define NODO_NUMERO              (9LL)
#define NODO_DECIMAL             (10LL)
#define NODO_CADENA_LIT          (11LL)
#define NODO_BINARIA             (12LL)
#define NODO_UNARIA              (13LL)
#define NODO_LLAMADA             (14LL)
#define NODO_PARAMETRO           (15LL)
#define NODO_ESTRUCTURA          (16LL)
#define NODO_IMPORTAR            (17LL)
#define NODO_LANZAR              (18LL)
#define NODO_ESCUCHAR            (19LL)
#define NODO_ROMPER              (20LL)
#define NODO_SIGUIENTE           (21LL)
#define NODO_BOOLEANO            (22LL)
#define NODO_CONSTANTE           (23LL)
#define NODO_INSEGURO            (24LL)
#define NODO_IMPORTAR_C          (25LL)
#define NODO_EXTERNO             (26LL)
#define NODO_RECUPERAR           (27LL)
#define NODO_TENSOR              (28LL)
#define NODO_INDICE              (29LL)
#define NODO_TRANSFERIDO         (30LL)
#define NODO_ACCESO_CAMPO        (31LL)
#define NODO_ASIGNACION_CAMPO    (32LL)
#define NODO_PARRAFO             (33LL)
#define NODO_DECLARACION         (34LL)
#define NODO_LOG                 (35LL)
#define NODO_PUNTERO             (36LL)
#define NODO_DEREF               (37LL)
#define NODO_COINCIDIR           (38LL)
#define NODO_CASO                (39LL)
#define NODO_ASM                 (40LL)
#define NODO_CANAL_CREAR         (41LL)
#define NODO_ENVIAR_CANAL        (42LL)
#define NODO_RECIBIR_CANAL       (43LL)
#define NODO_VACIO               (44LL)
#define NODO_PARA                (45LL)
#define NODO_CONTRATO            (46LL)
#define NODO_NULO                (47LL)
#define NODO_LET                 (48LL)
#define NODO_DELEGAR             (49LL)
#define NODO_EXPORT              (50LL)
#define NODO_DECLARACION_TIPO    (51LL)
#define NODO_CONSTRUCTOR         (52LL)
#define NODO_PROPAGAR            (53LL)
#define NODO_INTENTO             (54LL)
#define NODO_LISTA_LIT           (55LL)
#define NODO_MAPA_LIT            (56LL)
#define NODO_PARA_EN             (57LL)
#define NODO_BLOQUE_SQ           (58LL)

#endif /* AST_NODOS_H */
